export const LOGIN_USER = 'LOGIN_USER'; // fetch
export const LOGOUT_USER = 'LOGOUT_USER'; //fetch
export const RESUME_SESIION = 'RESUME_SESSION';

export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER';

export const SET_USER_ERR = 'SET_USER_ERR';
export const SET_NOTICEBOARD_ERR = 'SET_NOTICEBOARD_ERR';
export const REMOVE_NOTICEBOARD_ERR = 'REMOVE_NOTICEBOARD_ERR';
export const REMOVE_USER_ERR = 'REMOVE_USER_ERR';

export const SET_NOTICEBOARD ='SET_NOTICEBOARD';
export const REMOVE_NOTICEBOARD = 'REMOVE_NOTICEBOARD';
export const GET_NOTICEBOARD = 'GET_NOTICEBOARD'; // fetch
